# Generated by Django 3.2.6 on 2021-08-30 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(null=True, upload_to='article/')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('region', models.CharField(choices=[('서울특별시', '서울특별시'), ('경기도', '경기도'), ('강원도', '강원도'), ('충청도', '충청도'), ('전라도', '전라도'), ('경상도', '경상도'), ('제주도', '제주도')], default=True, max_length=10)),
                ('progress_method', models.CharField(choices=[('전체', '전체'), ('어학', '어학'), ('취업', '취업'), ('고시/공무원', '고시/공무원'), ('취미/교양', '취미/교양'), ('프로그래밍', '프로그래밍'), ('기타', '기타')], default=True, max_length=10)),
                ('max_personnel', models.CharField(choices=[('상관없음', '상관없음'), ('1~2명', '1~2명'), ('3~4명', '3~4명'), ('5~6명', '5~6명'), ('6명이상', '6명이상')], default=True, max_length=10)),
                ('hits', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
