# Generated by Django 3.2.6 on 2021-09-07 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0003_auto_20210831_1455'),
        ('commentapp', '0002_comment_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='freearticle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='free_comments', to='articleapp.article'),
        ),
    ]
