# Generated by Django 3.2.6 on 2021-09-07 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commentapp', '0003_comment_freearticle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='freearticle',
        ),
    ]
