# Generated by Django 3.2.6 on 2021-09-14 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freearticleapp', '0002_rename_article_freearticle'),
        ('commentapp', '0005_comment_freearticle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='freearticle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='free_comments', to='freearticleapp.freearticle'),
        ),
    ]
