# Generated by Django 3.2.6 on 2021-08-21 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountsapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
